In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
from pathlib import Path

import numpy as np
import torch
import torch as tr
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision as tv
from torchvision.transforms import v2
import pandas as pd
import matplotlib.pyplot as plt
import mplcyberpunk

plt.style.use("cyberpunk")

%matplotlib inline

In [3]:
logits = torch.randn((10, 2))
logits

tensor([[ 1.9059, -0.1579],
        [-0.5399,  1.2146],
        [ 0.7667,  0.7282],
        [-0.3059,  1.1096],
        [-0.4889, -0.2376],
        [-1.9178, -0.3757],
        [ 0.7890, -0.4473],
        [ 0.2859,  1.7787],
        [ 0.3899,  1.1325],
        [-0.3305, -1.1718]])

In [4]:
logits.argmax(dim=1)

tensor([0, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [6]:
F.softmax(logits, dim=1).argmax(dim=1)

tensor([0, 1, 0, 1, 1, 1, 0, 1, 1, 0])